server:
  port: 8888
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  application:
    name: webscoket
logging:
  level:
    root: INFO
    com:
      jackfree:
        webscoket: INFO
